### ISSUE TITLE
Curl download URL not found

### ISSUE THREAD

**Issue by asmae-toumi** [marcelomazza/homebrew-curl-libssh2#3]
Hi, 

It appears the download URL for curl is not found anymore (Please see screenshot). I'd appreciate your help on how to update the URL. Thanks.

<img width="1021" alt="install_error" src="https://user-images.githubusercontent.com/55239808/109505980-25d90100-7a6b-11eb-837c-ce1f50871c6f.png">

**Comment by marcelomazza** [comment]
Thanks @asmae-toumi. I just checked and I have the same issue.

I don't have the time to investigate further, I'll leave the issue open to see if anyone else can collaborate, otherwise I'll probably archive the repository.

Sorry I can't help more!

**Comment by asmae-toumi** [comment]
Thank you. I was able to successfully get the latest curl version from homebrew which has sftp support and recompile the R package I needed using the instructions found [here](https://github.com/jeroen/curl/).
